identifier = "RSSOrigin2-JupiterMoons"
name = "RSS-Origin 2 - JupiterMoons"
abstract = "This pack includes 10 extra moons for Jupiter: Amalthea | Himalia | Elara | Pasiphae | Carme | Ananke | Thebe | Adrastea | Metis | Themisto."
tags = ["config", "planet-pack"]
license = "CC-BY-NC-SA-4.0"
authors = ["Charon_S"]
ksp_version = "1.12"
repo = "CharonSSS/RSS-Origin-2-JupiterMoons"
asset_match = "RSSOrigin2-JupiterMoons.zip"

[resources]
manual = "https://github.com/CharonSSS/RSS-Origin-2/wiki"
homepage = "https://github.com/CharonSSS/RSS-Origin-2"

[[install]]
file = "GameData/RSSOrigin2"
install_to = "GameData"

[dependencies]
RSSOrigin2-Core = "*"

[recommends]

[conflicts]