identifier = "RSSOrigin2-MainBeltAsteroids-SizeI"
name = "RSS-Origin 2 - MainBeltAsteroids-SizeI"
abstract = "This pack includes 18 MBAs with diameter < 100km and 6 moons: Lutetia | Virginia | Antiope, S/2000 (90) 1 | Rosa | Ida, Dactyl | Mathilde | Nike | Gaspra | Masursky | Šteins | Balam, S/2002 (3749) 1, S/2007 (3749) 1 | Annefrank | Bro | Scottmanley | Donaldjohanson | APL | Dinkinesh, Selam | 2006 VW139, S/2011 (300163) 1."
tags = ["config", "planet-pack"]
license = "CC-BY-NC-SA-4.0"
authors = ["Charon_S"]
ksp_version = "1.12"
repo = "CharonSSS/RSS-Origin-2-MainBeltAsteroids"
asset_match = "RSSOrigin2-MainBeltAsteroids-SizeI.zip"

[resources]
manual = "https://github.com/CharonSSS/RSS-Origin-2/wiki"
homepage = "https://github.com/CharonSSS/RSS-Origin-2"

[[install]]
file = "GameData/RSSOrigin2"
install_to = "GameData"

[dependencies]
RSSOrigin2-Core = "*"

[recommends]

[conflicts]