identifier = "RSSOrigin2-NearEarthObjects-SizeII"
name = "RSS-Origin 2 - NearEarthObjects-SizeII"
abstract = "This pack includes 13 NEOs with diameter > 2km and 6 moons: Eros | Ganymed | Florence, S/2017 (3122) 1, S/2017 (3122) 2 | Don Quixote | 2001 SN263, S/2008 (153591) 1, S/2008 (153591) 2 | Geographos | Daedalus | Phaethon | Toutatis | Heracles, S/2011 (5143) 1 | Ra-Shalom | Cruithne | Atira, S/2017 (163693) 1."
tags = ["config", "planet-pack"]
license = "CC-BY-NC-SA-4.0"
authors = ["Charon_S"]
ksp_version = "1.12"
repo = "CharonSSS/RSS-Origin-2-NearEarthObjects"
asset_match = "RSSOrigin2-NearEarthObjects-SizeII.zip"

[resources]
manual = "https://github.com/CharonSSS/RSS-Origin-2/wiki"
homepage = "https://github.com/CharonSSS/RSS-Origin-2"

[[install]]
file = "GameData/RSSOrigin2"
install_to = "GameData"

[dependencies]
RSSOrigin2-Core = "*"

[recommends]

[conflicts]