identifier = "RSSOrigin2-InterstellarObjects"
name = "RSS-Origin 2 - InterstellarObjects"
abstract = "This pack includes 3 Interstellar objects: 1I/ʻOumuamua | 2I/Borisov | 3I/ATLAS."
tags = ["config", "planet-pack"]
license = "CC-BY-NC-SA-4.0"
authors = ["Charon_S"]
ksp_version = "1.12"
repo = "CharonSSS/RSS-Origin-2-InterstellarObjects"
asset_match = "RSSOrigin2-InterstellarObjects.zip"

[resources]
manual = "https://github.com/CharonSSS/RSS-Origin-2/wiki"
homepage = "https://github.com/CharonSSS/RSS-Origin-2"

[[install]]
file = "GameData/RSSOrigin2"
install_to = "GameData"

[dependencies]
RSSOrigin2-Core = "*"

[recommends]

[conflicts]