identifier = "RSSOrigin2-MissionPack-Stardust"
name = "RSS-Origin 2 - MissionPack-Stardust"
abstract = "This pack includes 3 objects for the Stardust mission: Annefrank | 9P/Tempel 1 | 81P/Wild 2."
tags = ["config", "planet-pack"]
license = "CC-BY-NC-SA-4.0"
authors = ["Charon_S"]
ksp_version = "1.12"
repo = "CharonSSS/RSS-Origin-2-MissionPack-Stardust"
asset_match = "RSSOrigin2-MissionPack-Stardust.zip"

[resources]
manual = "https://github.com/CharonSSS/RSS-Origin-2/wiki"
homepage = "https://github.com/CharonSSS/RSS-Origin-2"

[[install]]
file = "GameData/RSSOrigin2"
install_to = "GameData"

[dependencies]
RSSOrigin2-Core = "*"

[recommends]

[conflicts]
RSSOrigin2-Comets = "*"
RSSOrigin2-MainBeltAsteroids-SizeI = "*"